name: Bug report
description: Create a report to help us improve
title: "bug: "
labels: ["bug"]
body:
  - type: input
    attributes: { label: What happened? }
  - type: textarea
    attributes: { label: Steps to reproduce }
  - type: input
    attributes: { label: Environment (browser/OS) }
  - type: textarea
    attributes: { label: Screenshots / logs }
