name: Feature request
description: Suggest an idea for this project
title: "feat: "
labels: ["feature"]
body:
  - type: textarea
    attributes: { label: Problem statement }
  - type: textarea
    attributes: { label: Proposed solution }
  - type: textarea
    attributes: { label: Alternatives considered }
