name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: "pnpm" }
      - run: pnpm i
      - run: pnpm typecheck
      - run: pnpm lint --max-warnings=0
      - run: pnpm -w build
      - run: pnpm test

      - name: License allowlist
        run: pnpm node scripts/license-check.mjs

      - name: Build OpenAPI
        run: pnpm --filter @carelink/api openapi:build
