name: k6 Smoke
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm i
      - name: Build web
        run: pnpm --filter @carelink/web build
      - name: Start web
        working-directory: apps/web
        run: nohup pnpm start &
      - name: Wait for server
        run: npx wait-on http://localhost:3000
      - name: Run k6
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/k6-smoke.js
