name: Security Scans
on:
  pull_request: { branches: [main] }
  push: { branches: [main] }
  workflow_dispatch:
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          redact: true
  osv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: "pnpm" }
      - run: pnpm i --frozen-lockfile=false
      - name: OSV scan
        uses: google/osv-scanner-action@v1.8.5
        with: { scan-args: "-r ." }
