name: Spellcheck
on:
  pull_request:
  workflow_dispatch:

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g cspell
      - run: cspell lint --no-must-find-files .
